#  menu items
[[main]]
  name = "Blog"
  weight = 1
  url = "blog/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[main]]
  name = "Legal"
  weight = 5
  url = "legal/"

[[main]]
  name = "Download"
  weight = 3
  url = "https://github.com/cinderblocks/radegast/releases"

[[main]]
  name = "Discussion"
  weight = 4
  url = "https://github.com/cinderblocks/radegast/discussions"
